### ISSUE TITLE
Class 'Split' not found

### ISSUE THREAD

**Issue by donnekgit** [Callwoola/php-split#6]
I've run composer in the php-split dir and installed the dependencies.  Then I create a file testme.php:
```
<?php
require __DIR__ .'/vendor/autoload.php';
$split = new Split();
var_dump($split->simple("您好 phpSplit"));
$this->assertTrue(True);
?>
```
and put that in the php-split dir.  When I run `php testme.php`, I get:
`Fatal error: Class 'Split' not found`

How can I fix this?

On a subsidiary point, how many of the dependencies downloaded are essential for running php-split - many of them seem to be unit-test related?

**Comment by Callwoola** [comment]
Thinks @donnekgit 

this's my fault

I Fixed that.
```php
require __DIR__ .'/vendor/autoload.php';
$split = new \phpSplit\Split\Split();
var_dump($split->simple("您好 phpSplit"));
```

and I think TestCase's dependencies  was necessary . although very redundant.
